# Generated by Django 3.0.7 on 2020-07-02 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_auto_20200702_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='to_user',
        ),
        migrations.AddField(
            model_name='friend',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
