# Generated by Django 3.0.7 on 2020-07-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200702_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='users.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
    ]
